---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-go-deployment
spec:
  template:
    spec:
      containers:
        - name: backend-go
          env:
            - name: UI_THEME
              value: "light"
            - name: CACHE_SIZE
              value: "2048kb"
            - name: PAGE_LIMIT
              value: "25"
            - name: SORTING
              value: "ascending"
            - name: N_BUCKETS
              value: "42"
