---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-go-deployment
spec:
  template:
    spec:
      containers:
        - name: backend-go
          env:
            - name: ENV
              value: "sit"
            - name: FEATURE_A_ENABLED
              value: "1"
